spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username:
    password:
    schema:
    url: jdbc:postgresql://url/db
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema:
springdoc:
  api-docs:
    path: /api-docs